name: CI
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: "npm install"
      run: npm ci

    - name: "Lint scss"
      run: npm run lint:scss

    - name: 'Automated Version Bump'
      id: 'version-bump'
      uses: 'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: "Update version.php"
      run: ./update-version

    - name: "stories-map / npm install"
      working-directory: widgets/stories-map
      run: "npm ci"

    - name: "stories-map / build"
      working-directory: widgets/stories-map
      run: "npm run build"

    - name: "Create plugin bundle"
      run: npm run bundle
    
    - name: Upload plugin package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vikalpsangam.org-plugin.zip
        asset_name: vikalpsangam.org-plugin-${{ steps.version-bump.outputs.newTag }}.zip
        tag: ${{ steps.version-bump.outputs.newTag }}
        overwrite: true
        body: "Wordpress Plugin for vikalpsangam.org. Version ${{ steps.version-bump.outputs.newTag }}"
      

    - name: Deploy Plugins to WP Server
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.DEPLOYMENT_USER }}
        host: ${{ secrets.DEPLOYMENT_HOST }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        source: "vikalpsangam.org-plugin.zip"
        target: "/tmp"
        port: 22

    - name: Install plugin using Wordpress cli over ssh
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.DEPLOYMENT_USER }}
        host: ${{ secrets.DEPLOYMENT_HOST }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        port: 22
        script: |
          sudo wp plugin install /tmp/vikalpsangam.org-plugin.zip \
            --activate \
            --allow-root \
            --path=/var/www/html \
            --force

