name: deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'     
        required: true
      version:
        description: 'Version to deploy'     
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment }}
    steps:
    - name: Fetch plugin release asset
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: tags/${{github.event.inputs.version}}
        file: "vikalpsangam.org-plugin-${{github.event.inputs.version}}.zip"
        target: "vikalpsangam.org-plugin.zip"

    - name: Copy plugin to server
      run: >
        echo ${{ secrets.SSH_KEY }} > ssh.key
        scp -i ssh.key vikalpsangam.org-plugin.zip {{secrets.USER}}@{{secrets.HOST}}:/tmp

    - name: Install plugin using Wordpress cli over ssh
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo wp plugin install /tmp/vikalpsangam.org-plugin.zip \
            --activate \
            --allow-root \
            --path=/var/www/html \
            --force