name: Deploy Prod
on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version to deploy"
                required: true
jobs:
    deploy:
        environment:
            name: prod
            url: https://vikalpsangam.org
        runs-on: ubuntu-latest
        steps:
            - name: Install plugin using Wordpress cli over ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  proxy_host: ${{ secrets.PROXY_HOST }}
                  proxy_username: ${{ secrets.PROXY_USERNAME }}
                  proxy_key: ${{ secrets.PROXY_KEY }}
                  script: |
                      wget https://github.com/${{github.repository}}/releases/download/${{github.event.inputs.version}}/vikalpsangam.org-plugin-${{github.event.inputs.version}}.zip -O /tmp/vikalpsangam.org-plugin.zip
                      sudo wp theme install /tmp/vikalpsangam.org-plugin.zip \
                        --activate \
                        --allow-root \
                        --path=${{ secrets.WORDPRESS_PATH }} \
                        --force
