name: Deploy Dev
on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version to deploy"
                required: true
jobs:
    deploy:
        environment:
            name: dev
            url: https://dev.vikalpsangam.org
        runs-on: ubuntu-latest
        steps:
            - name: Install plugin using Wordpress cli over ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      wget https://github.com/${{github.repository}}/releases/download/${{github.event.inputs.version}}/vikalpsangam.org-${{github.event.inputs.version}}-plugin.zip -O /tmp/vikalpsangam.org-plugin.zip
                      sudo wp plugin install /tmp/vikalpsangam.org-plugin.zip \
                        --activate \
                        --allow-root \
                        --path=${{ secrets.WORDPRESS_PATH }} \
                        --force
