name: deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'     
        required: true
      version:
        description: 'Version to deploy'     
        required: true
jobs:
  deploy:
    environment: 
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Install plugin using Wordpress cli over ssh
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          wget https://github.com/${{github.repository}}/releases/download/${{github.event.inputs.version}}/vikalpsangam.org-plugin-${{github.event.inputs.version}}.zip -O /tmp/vikalpsangam.org-plugin.zip
          sudo wp plugin install /tmp/vikalpsangam.org-plugin.zip \
            --activate \
            --allow-root \
            --path=${{ secrets.WORDPRESS_PATH }} \
            --force