name: deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'     
        required: true
      version:
        description: 'Version to deploy'     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - name: Fetch Latest Release
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: "latest"
        file: "vikalpsangam.org-plugin-${{inputs.version}}.zip"
        target: "vikalpsangam.org-plugin.zip"

    - name: Copy Plugins to WP Server
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        source: "vikalpsangam.org-plugin"
        target: "/tmp"
        port: 22

    - name: Install plugin using Wordpress cli over ssh
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          sudo wp plugin install /tmp/vikalpsangam.org-plugin.zip \
            --activate \
            --allow-root \
            --path=/var/www/html \
            --force