name: deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'     
        required: true
        default: 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - name: Deploy Plugins to WP Server
      uses: appleboy/scp-action@master
      with:
        username: ${{ secrets.DEPLOYMENT_USER }}
        host: ${{ secrets.DEPLOYMENT_HOST }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        source: "vikalpsangam.org-plugin.zip"
        target: "/tmp"
        port: 22

    - name: Install plugin using Wordpress cli over ssh
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          sudo wp plugin install /tmp/vikalpsangam.org-plugin.zip \
            --activate \
            --allow-root \
            --path=/var/www/html \
            --force

